import Head from "next/head";
import Hero from "~/layout/Intro/Hero";
import Sticky from "~/layout/Intro/Sticky";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[400vh]">
        <Sticky/>
        <Hero/>
      </main>
    </>
  );
}